# Generated by Django 4.2.2 on 2023-07-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='Banner',
        ),
    ]
