# Generated by Django 4.2.2 on 2023-07-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_banner_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='cat_images/')),
            ],
            options={
                'verbose_name_plural': '2.Categories',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': '1.Banners'},
        ),
    ]
