# Generated by Django 4.2.2 on 2023-07-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_delete_service_alter_banners_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
    ]
