# Generated by Django 4.2.2 on 2023-07-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subplan_subplanfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplans',
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='subplans',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
