# Generated by Django 4.2.2 on 2023-07-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_appsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
    ]
