# Generated by Django 4.2.2 on 2023-07-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_appsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='app_logos/'),
        ),
    ]
